name = "JuBounds"
uuid = "06be1f3b-e9c8-4890-afa6-06140c2b7f85"
authors = ["Arie Beresteanu <arie@pitt.edu>", "Yunyun LV <yunyun.lv.23@gmail.com>"]
version = "0.1.0"
[deps]  
Statistics = "1.9"
Parameters = "0.12"
